name: GitHub Metrics 🐾
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: 🐈 General & Languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nekoraru22
          base: header, community, repositories, metadata
          base_indepth: yes
          config_timezone: Europe/Madrid
          
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_introduction: yes

      - name: 🐈 Achievements & Activity
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nekoraru22
          base: ""
          config_timezone: Europe/Madrid
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: projects, job, polyglot, runner 
          
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14
          plugin_fortune: yes
          
          plugin_traffic: yes
